### ISSUE TITLE
Question. About npm test

### ISSUE THREAD

**Issue by msdickinson** [asu-ke-web-services/dont-get-fired-game#112]
I am geting no lint issues. But when i pull the latest, to my branch (same with tyuen)
"Cannot find module 'redux'"

I assume I am doing something wrong in source control. Ill finish all my sections. but I would like to resolve this. I did run "git pull origin develop" Before starting, Tyuen has the same issue.

C:\Users\marks\Capstone\dont-get-fired-game>npm test

> sustainability-game@0.0.1 test C:\Users\marks\Capstone\dont-get-fired-game
> npm run lint && npm run testonly
> 
> sustainability-game@0.0.1 lint C:\Users\marks\Capstone\dont-get-fired-game
> eslint ./libs ./client ./server --ext .js --ext .jsx
> 
> sustainability-game@0.0.1 testonly C:\Users\marks\Capstone\dont-get-fired-game
> mocha --require .scripts/mocha_runner client/**/tests/**/_.js client/__/tests/__/_.jsx

module.js:339
    throw err;
    ^

Error: Cannot find module 'redux'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\client\stores\game-store.js:8:14)
    at Module._compile (module.js:435:26)
    at loader (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\babel-core\node_modules\babel-register\lib\node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js](C:UsersmarksCapstonedont-get-fired-gamenode_modulesbabel-corenode_modulesbabel-registerlibnode.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\client\components\game\program-list-item\program-list-item.jsx:11:18)
    at Module._compile (module.js:435:26)
    at loader (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\babel-core\node_modules\babel-register\lib\node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .jsx](C:UsersmarksCapstonedont-get-fired-gamenode_modulesbabel-corenode_modulesbabel-registerlibnode.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\client\components\game\program-list-item\tests\program-list-item.jsx:11:24)
    at Module._compile (module.js:435:26)
    at loader (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\babel-core\node_modules\babel-register\lib\node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .jsx](C:UsersmarksCapstonedont-get-fired-gamenode_modulesbabel-corenode_modulesbabel-registerlibnode.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (C:\Users\marks\Capstone\dont-get-fired-game\node_modules\mocha\bin_mocha:403:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "testonly"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sustainability-game@0.0.1 testonly: `mocha --require .scripts/mocha_runner client/**/tests/**/*.js client/**/tests/**/*.jsx`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sustainability-game@0.0.1 testonly script 'mocha --require .scripts/mocha_runner client/**/tests/**/_.js client/__/tests/__/_.jsx'.
npm ERR! This is most likely a problem with the sustainability-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --require .scripts/mocha_runner client/**/tests/**/_.js client/__/tests/__/_.jsx
npm ERR! You can get their info via:
npm ERR!     npm owner ls sustainability-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marks\Capstone\dont-get-fired-game\npm-debug.log
npm ERR! Test failed.  See above for more details.

C:\Users\marks\Capstone\dont-get-fired-game>

**Comment by idmontie** [comment]
Did you run `npm install`?

**Comment by msdickinson** [comment]
That Fixed it.
